---
- name: Generate
  hosts: sw
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network

  tasks:
    - name: SET VLAN
      vars:
        vlan_items: "{{ range(1, num_vlans + 1) | map('string') | list }}"
      block:
        - name: Create VLAN name 
          community.network.exos_config:
            lines: 
                - "create vlan {{ lookup('vars', 'VLAN_NAME_' + item) }}"
          loop: "{{ vlan_items }}"
          ignore_errors: True


         