---
- name: Generate
  hosts: sw
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network


  tasks:
    - name: Create a file new3_file.txt and push to GitHub
      block:
        - name: Show config
          community.network.exos_command:
            commands: show config
          register: config

        - name: SAVE OUTPUT TO ./backups/
          copy:
            content: "{{ config.stdout[0] }}"
            dest: "/tmp/{{ inventory_hostname }}.txt"
          delegate_to: localhost
          become: false

        - name: Add exception for /tmp directory in Git
          command: git config --global --add safe.directory /tmp
          when: not ansible_check_mode
          run_once: true
          delegate_to: localhost

        - name: Clone the existing GitHub repository
          args: 
            chdir: /tmp
          command: git clone https://github.com/shezanhossain2/fresh.git
          run_once: true
          delegate_to: localhost

        - name: create directory
          file :
            path: /tmp/fresh
            state: directory
          run_once: true
          delegate_to: localhost

        - name: Copy new3_file.txt to sw.txt
          args: 
            chdir: /tmp
          command: cp /tmp/{{ inventory_hostname }}.txt /tmp/fresh/
          changed_when: false
          when: not ansible_check_mode
          delegate_to: localhost

        - name: push to git
          ignore_errors: true
          shell: "{{ item }}"
          args: 
            chdir: /tmp/fresh 
          loop: 
            - git config --global user.name "shezanhossain2"
            - git config --global user.email hossainmahmudshezan@gmail.com
            - git init
            - git add *
            - git commit -m "{{inventory_hostname}}"
            - git branch -M master
            - git remote add origin https://{{token_key}}@github.com/{{user_name}}/fresh.git 
            - git push origin master
          delegate_to: localhost
          become: false