---
- name: Generate
  hosts: sw
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network


  tasks:
    - name: Match config
      vars:
        vlan_items: "{{ range(1, num_vlans + 1) | map('string') | list }}"
      block:
        - name: Show config
          community.network.exos_command:
            commands: show config
          register: config

        - name: SAVE OUTPUT TO ./backups/
          copy:
            content: "{{ config.stdout[0] }}"
            dest: "/tmp/{{ inventory_hostname }}.txt"
          delegate_to: localhost
          become: false

        - name: Validation of VLAN Name 
          ansible.builtin.lineinfile: 
            path: "/tmp/{{ inventory_hostname }}.txt"
            line: "create vlan \"{{ lookup('vars', 'VLAN_NAME_' + item) }}\""
            state: present
          check_mode: true
          register: conf_name
          failed_when: (conf_name is changed) or (conf_name is failed)
          loop: "{{ vlan_items }}"
          delegate_to: localhost

        - name: Validation of VLAN Tag
          ansible.builtin.lineinfile: 
            path: "/tmp/{{ inventory_hostname }}.txt"
            line: "configure vlan {{ lookup('vars', 'VLAN_NAME_' + item) }} tag {{ lookup('vars', 'TAG_ID_' + item) }}"
            state: present
          check_mode: true
          register: conf_tag  
          failed_when: (conf_tag is changed) or (conf_tag is failed)
          loop: "{{ vlan_items }}"
          delegate_to: localhost

        - name: Display debug message
          ansible.builtin.debug: 
            msg: "{{ conf_tag }}"
