---
- name: Generate
  hosts: sw
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network

  tasks:
    - name: Create a file new3_file.txt and push to GitHub
      block:
        - name: Show config
          community.network.exos_command:
            commands: show config
          register: current_config

        - name: Check if 'create vlan IG' exists in the config
          set_fact:
            vlan_found: "{{ 'create vlan IG' in current_config.stdout }}"

        - name: Fail the job if 'create vlan IG' is not found
          fail:
            msg: "VLAN IT not found in config"
          when: not vlan_found
