---
- name: Generate
  hosts: sw
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network


  tasks:
    - name: Create a file new3_file.txt and push to GitHub
      block:
        - name: Show config
          community.network.exos_command:
            commands: show config
          register: config

        - name: SAVE OUTPUT TO ./backups/
          copy:
            content: "{{ config.stdout[0] }}"
            dest: "/tmp/{{ inventory_hostname }}.txt"
          delegate_to: localhost
          become: false

        - name: Check if 'create vlan IG' exists in the file
          ansible.builtin.lineinfile:
            path: "/tmp/{{ inventory_hostname }}.txt"  # Replace with your file path
            regexp: "^create vlan IG$"
            state: present
          check_mode: true
          register: vlan_check_result

        - name: Notify if 'create vlan IG' is found
          debug:
            msg: "Line 'create vlan IG' found in the file."
          when: vlan_check_result.matches
