---
- name: Determine directory for secret2.yml file
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get current working directory
      shell: pwd
      register: current_directory
      delegate_to: localhost
      become: false

    - name: Display directory for secret2.yml
      debug:
        msg: "Place secret2.yml in directory: {{ current_directory.stdout }}"
