---
- name: ansible-vault test playbook
  hosts: all
  vars_files:
    - secret2.yml

  tasks:
    - name: show vault encrypted variables
      debug: 
        msg: "{{ user_name }} and {{ token_key }}"
