- name: Retrieve extra_vars from AWX job
  hosts: localhost  # Or specify your target hosts here
  tasks:
    - name: Get extra_vars from AWX job
      uri:
        url: "https://your-awx-instance/api/v2/jobs/{{ job_id }}/extra_vars/"
        method: GET
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ token_api }}"
        validate_certs: no  # Change this to yes if your AWX instance has valid SSL certificates
      register: extra_vars_response

    - name: Display extra_vars
      debug:
        var: extra_vars_response.json
