---
- name: ansible-vault test playbook
  hosts: all
  vars_files:
    - /var/lib/awx/projects/secrect2.yml

  tasks:
    - name: show vault encrypted variables
      debug: 
        msg: "{{ user_name }} and {{ token_key }}"
      delegate_to: localhost
      become: false