---
- name: Generate
  hosts: sw
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network


  tasks:
    - name: Match config
      vars:
        vlan_items: "{{ range(1, num_vlans + 1) | map('string') | list }}"
      block:
        - name: Show config
          community.network.exos_command:
            commands: show config
          register: config

        - name: SAVE OUTPUT TO ./backups/
          copy:
            content: "{{ config.stdout[0] }}"
            dest: "/tmp/{{ inventory_hostname }}.txt"
          delegate_to: localhost
          become: false

        - name: Check whether /tmp/my.conf contains "127.0.0.1"
          command: grep -Fxq "configure vlan IT add ports 2 tagged" /tmp/{{ inventory_hostname }}.txt
          register: checkmyconf
          check_mode: no
          ignore_errors: yes
          changed_when: no


        - name: Greet the world if /tmp/my.conf contains "127.0.0.1"
          debug: msg="Hello, world!"
          when: checkmyconf.rc == 0
