---
- name: Generate
  hosts: sw
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network


  tasks:
    - name: Match config
      vars:
        vlan_items: "{{ range(1, num_vlans + 1) | map('string') | list }}"
      block:
        - name: Show config
          community.network.exos_command:
            commands: show config
          register: config

        - name: SAVE OUTPUT TO ./backups/
          copy:
            content: "{{ config.stdout[0] }}"
            dest: "/tmp/{{ inventory_hostname }}.txt"
          delegate_to: localhost
          become: false

        - name: Read contents of the file into a variable
          ansible.builtin.shell: cat /tmp/{{ inventory_hostname }}.txt
          register: file_contents

        - name: Define list of expected VLAN port assignment lines
          set_fact:
            expected_lines:
              - "configure vlan IT add ports 2 tagged"
              - "configure vlan HR add ports 3 tagged"
              # Add other expected lines here based on your VLAN items

        - name: Assert all expected lines are in the file
          ansible.builtin.assert:
            that:
              - item in file_contents.stdout_lines
            fail_msg: "Line '{{ item }}' is missing in the file."
          loop: "{{ expected_lines }}"


