---
- name: Generate
  hosts: sw
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network


  tasks:
    - name: Match config
      vars:
        vlan_items: "{{ range(1, num_vlans + 1) | map('string') | list }}"
      block:
        - name: Show config
          community.network.exos_command:
            commands: show config
          register: config

        - name: SAVE OUTPUT TO ./backups/
          copy:
            content: "{{ config.stdout[0] }}"
            dest: "/tmp/{{ inventory_hostname }}.txt"
          delegate_to: localhost
          become: false


        - name: Validation of Port assignment with tagged or untagged
          block:
            - name: Validation of Port assignment with tagged or untagged
              ansible.builtin.lineinfile: 
                path: "/tmp/{{ inventory_hostname }}.txt"
                line: "configure vlan IT add ports 2 tagged"
                state: present
              check_mode: true
              delegate_to: localhost
              register: conf_port
              failed_when: (conf_port is changed) or (conf_port is failed)
              ignore_errors: true       