---
- name: Generate VLAN
  hosts: sw
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Set VLANs
      vars:
        vlan_items: "{{ range(1, num_vlans + 1) | map('string') | list }}"
      block:
        - name: Add Ports to VLAN
          debug:
            msg: "configure vlan {{ lookup('vars', 'VLAN_NAME_' + item)}} add ports {{lookup('vars', 'PORT_NUM_' + item)}} {{ lookup('vars', 'TAGGED_' + item) }}"
          loop: "{{ vlan_items }}"
          when: lookup('vars', 'PORT_NUM_' + item, default='') != ''

